version: "3"
services:
  nginx:
    image: chriswald/personal-website:latest
    ports:
      - "8080:80"
    networks:
      - internal
  php:
    image: chriswald/personal-website-php:latest
    networks:
      - internal
networks:
  internal:
    driver: bridge