name: ci

on:
  workflow_dispatch:
  push:
    branches:
      - "docker"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./nginx/Dockerfile
            tags: ${{ vars.DOCKERHUB_USERNAME }}/personal-website:latest
          - dockerfile: ./php/Dockerfile
            tags: ${{ vars.DOCKERHUB_USERNAME }}/personal-website-php:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tags }}
